name: firefolio
version: 1.0.0+1
publish_to: none
description: onFire's portfolio
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  rive: 0.9.0
  mouse_parallax: 1.1.0
  google_fonts: 3.0.1
  firebase_core: 1.18.0
  flutter_hooks: 0.18.5+1
  flutter_native_splash: 2.2.3+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/rive/
  uses-material-design: true

