// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmkp5xjEDyBVE25-kmF7dFOsSA7ml_T8Q',
    appId: '1:240711889577:web:89d3034b664f8ce5ee2fb8',
    messagingSenderId: '240711889577',
    projectId: 'abhi-firesome',
    authDomain: 'abhi-firesome.firebaseapp.com',
    storageBucket: 'abhi-firesome.appspot.com',
    measurementId: 'G-P544NC0Y52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5Zmh0EXHg1QflVzufeKO5v3EiE4hGUI',
    appId: '1:240711889577:android:76eff698547ffbe6ee2fb8',
    messagingSenderId: '240711889577',
    projectId: 'abhi-firesome',
    storageBucket: 'abhi-firesome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW8rzMjYbEhth99YZ_IS0WEyKeEN4Itgo',
    appId: '1:240711889577:ios:916551aa2d8d8e1cee2fb8',
    messagingSenderId: '240711889577',
    projectId: 'abhi-firesome',
    storageBucket: 'abhi-firesome.appspot.com',
    iosClientId: '240711889577-5puoj5mgv8cbs1svgojnfspk829akotl.apps.googleusercontent.com',
    iosBundleId: 'com.abhi.portfolio.firefolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW8rzMjYbEhth99YZ_IS0WEyKeEN4Itgo',
    appId: '1:240711889577:ios:916551aa2d8d8e1cee2fb8',
    messagingSenderId: '240711889577',
    projectId: 'abhi-firesome',
    storageBucket: 'abhi-firesome.appspot.com',
    iosClientId: '240711889577-5puoj5mgv8cbs1svgojnfspk829akotl.apps.googleusercontent.com',
    iosBundleId: 'com.abhi.portfolio.firefolio',
  );
}
